version: "3"

services:
  server:
    build: ./server
    container_name: server-node
    restart: always
    ports:
      - "5000:5000"
    external_links:
      - mongo

  mongo:
    image: mongo
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    external_links:
      - mongo
