# Use the official MongoDB image from Docker Hub
FROM mongo

# Create a directory to store the MongoDB data
RUN mkdir -p /data/db

# Set the /data/db directory as the working directory
WORKDIR /data/db

# Expose the default MongoDB port (27017)
EXPOSE 27017